---
abstract: 'minimalistic Supervisor'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Parallel::Scoreboard: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Proclet
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Validator: 0
  Getopt::Compact::WithCmd: 0.2
  Log::Minimal: 0.14
  Mouse: 0
  Parallel::Prefork: 0.13
  Term::ANSIColor: 0
  YAML::XS: 0.38
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/kazeburo/Proclet.git
version: 0.21
